site_name: "Application de traitement d'images"
site_description: "Documentation utilisateur d'une application de traitement d'images"
site_url: "https://bright4lpha.github.io/documentation_uti"
site_author: "Mathilde Henrion"

theme:
    name: "material"
    language: "fr"
    logo: "images/logo.png"
    favicon: "images/logo.png"
    palette:
        - media: "(prefers-color-scheme: light)"
          primary: green
          accent: light-green
          toggle:
              icon: material/weather-night
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: green
          accent: light-green
          toggle:
              icon: material/weather-sunny
              name: Switch to light mode
    features:
        - navigation.footer
nav:
    - Accueil: index.md
    - Documentation: traitement_images_doc.md
    - Définitions: definitions.md

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - admonition
    - mdx_math
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
